using Sandbox;
using SboxUiDesigner.Runtime;

namespace Sandbox.Samples;

/// <summary>
/// Companion Component for the <c>survival_hud_aaa</c> showcase sample - the
/// "AAA survival" HUD that demonstrates five live stat bars (Health, Hunger,
/// Thirst, Temperature, Stamina), a biome-driven full-screen tint, and a brief
/// red damage-flash overlay when the player takes damage.
///
/// <para>Drop this on a GameObject in the scene, hit Play, and the stats card
/// appears in the top-right corner. Use the <see cref="Health"/> / <see cref="Hunger"/>
/// / <see cref="Thirst"/> / <see cref="BodyTemp"/> / <see cref="Stamina"/> properties
/// in the Inspector to tweak values live, or call <see cref="TakeDamage"/> /
/// <see cref="Heal"/> / <see cref="Eat"/> / <see cref="Drink"/> / <see cref="Rest"/>
/// from gameplay code.</para>
///
/// <para>The wrapper class <c>SurvivalHudAaa</c> is generated by the SUI
/// Designer from <c>survival_hud_aaa.sui</c> on first compile, into
/// <c>Code/Samples/SurvivalHudAaa/</c> under the namespace <c>Sandbox.Samples</c>.</para>
/// </summary>
public sealed class SurvivalHudAaaController : Component
{
	// ─────────────────────────────────────────────────────────────────────────
	// Biome enum — controller-local, mapped to a tint color each tick.
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>Biome presets the controller knows how to tint. Add more if you wish.</summary>
	public enum Biome
	{
		/// <summary>No tint — bog-standard daytime gameplay.</summary>
		Default,
		/// <summary>Cool blue tint — snowy / arctic regions.</summary>
		Snow,
		/// <summary>Warm amber tint — desert / scorched regions.</summary>
		Desert,
		/// <summary>Sickly green tint — swamp / poisoned regions.</summary>
		Swamp,
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Public properties — exposed in the Inspector and bindable from anywhere.
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>The generated UI wrapper. Exposed so you can tweak it in the inspector if needed.</summary>
	[Property] public SurvivalHudAaa Hud { get; set; } = new();

	/// <summary>Current health. Clamped to [0, MaxHealth] every frame.</summary>
	[Property, Range( 0f, 999f ), Group( "Stats" )] public float Health { get; set; } = 100f;

	/// <summary>Maximum health. Drives the denominator and the bar normalization.</summary>
	[Property, Range( 1f, 999f ), Group( "Stats" )] public float MaxHealth { get; set; } = 100f;

	/// <summary>Current hunger (100 = stuffed, 0 = starving).</summary>
	[Property, Range( 0f, 999f ), Group( "Stats" )] public float Hunger { get; set; } = 100f;

	/// <summary>Maximum hunger.</summary>
	[Property, Range( 1f, 999f ), Group( "Stats" )] public float MaxHunger { get; set; } = 100f;

	/// <summary>Current thirst (100 = hydrated, 0 = parched).</summary>
	[Property, Range( 0f, 999f ), Group( "Stats" )] public float Thirst { get; set; } = 100f;

	/// <summary>Maximum thirst.</summary>
	[Property, Range( 1f, 999f ), Group( "Stats" )] public float MaxThirst { get; set; } = 100f;

	/// <summary>Body temperature on a 0..1 axis (0 = freezing, 0.5 = comfortable, 1 = burning).</summary>
	[Property, Range( 0f, 1f ), Group( "Stats" )] public float BodyTemp { get; set; } = 0.5f;

	/// <summary>Current stamina (100 = full, 0 = exhausted).</summary>
	[Property, Range( 0f, 999f ), Group( "Stats" )] public float Stamina { get; set; } = 100f;

	/// <summary>Maximum stamina.</summary>
	[Property, Range( 1f, 999f ), Group( "Stats" )] public float MaxStamina { get; set; } = 100f;

	/// <summary>
	/// Active biome. Drives <see cref="SurvivalHudAaa.BiomeTint"/> via a switch in
	/// <see cref="PushBiomeTint"/>. Change this from gameplay code (e.g. a biome
	/// trigger volume) and the screen tint follows on the next frame.
	/// </summary>
	[Property, Group( "World" )] public Biome ActiveBiome { get; set; } = Biome.Default;

	/// <summary>How long the red damage-flash overlay stays visible after each hit, in seconds.</summary>
	[Property, Range( 0.05f, 1.0f ), Group( "Effects" )] public float DamageFlashDuration { get; set; } = 0.3f;

	// ─────────────────────────────────────────────────────────────────────────
	// Private state.
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>Time since the last <see cref="TakeDamage"/> call — drives the damage-flash auto-hide.</summary>
	private TimeSince _timeSinceDamage = float.MaxValue;

	/// <summary>Whether the flash is currently up (so we only push the Variable on transitions, not every tick).</summary>
	private bool _flashVisible = false;

	// ─────────────────────────────────────────────────────────────────────────
	// Lifecycle.
	// ─────────────────────────────────────────────────────────────────────────

	protected override void OnStart()
	{
		// Passive mode — read-only HUD, never steals the cursor or keyboard.
		Hud.Show( SuiInputMode.Passive );
		PushAll();
	}

	protected override void OnUpdate()
	{
		// Clamp every stat each tick — easier than guarding every external mutation.
		if ( MaxHealth < 1f ) MaxHealth = 1f;
		if ( MaxHunger < 1f ) MaxHunger = 1f;
		if ( MaxThirst < 1f ) MaxThirst = 1f;
		if ( MaxStamina < 1f ) MaxStamina = 1f;

		Health = MathX.Clamp( Health, 0f, MaxHealth );
		Hunger = MathX.Clamp( Hunger, 0f, MaxHunger );
		Thirst = MathX.Clamp( Thirst, 0f, MaxThirst );
		Stamina = MathX.Clamp( Stamina, 0f, MaxStamina );
		BodyTemp = MathX.Clamp( BodyTemp, 0f, 1f );

		// Damage-flash auto-hide.
		if ( _flashVisible && _timeSinceDamage >= DamageFlashDuration )
		{
			_flashVisible = false;
			Hud.DamageFlashVisible = false;
		}

		// Built-in test hotkeys — Tab (Score action) takes 10 damage and
		// pulses the red overlay; R (Reload action) heals 25. Both actions
		// are mapped in the default s&box input layout so the sample works
		// drop-in without project-side configuration. Remove or remap when
		// you wire the HUD to real gameplay (call TakeDamage / Heal from
		// your own damage source).
		if ( Input.Pressed( "Score" ) ) TakeDamage( 10f );
		if ( Input.Pressed( "Reload" ) ) Heal( 25f );

		PushAll();
	}

	protected override void OnDestroy()
	{
		Hud?.Remove();
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Push helpers.
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>Push every stat into the SUI Variables in one shot.</summary>
	private void PushAll()
	{
		Hud.HealthFraction = MaxHealth > 0f ? Health / MaxHealth : 0f;
		Hud.HealthLabel    = $"{(int)Health}/{(int)MaxHealth}";

		Hud.HungerFraction = MaxHunger > 0f ? Hunger / MaxHunger : 0f;
		Hud.HungerLabel    = $"{(int)Hunger}/{(int)MaxHunger}";

		Hud.ThirstFraction = MaxThirst > 0f ? Thirst / MaxThirst : 0f;
		Hud.ThirstLabel    = $"{(int)Thirst}/{(int)MaxThirst}";

		Hud.TempFraction = BodyTemp;
		Hud.TempLabel    = TempLabelFor( BodyTemp );

		Hud.StaminaFraction = MaxStamina > 0f ? Stamina / MaxStamina : 0f;
		Hud.StaminaLabel    = $"{(int)Stamina}/{(int)MaxStamina}";

		PushBiomeTint();
	}

	/// <summary>Map <see cref="ActiveBiome"/> to a Color and push it into the Variable.</summary>
	private void PushBiomeTint()
	{
		// Low-alpha tints so the gameplay stays visible underneath. ~13%
		// alpha is enough to read as "I'm in a snow biome" without
		// drowning the world geometry.
		Hud.BiomeTint = ActiveBiome switch
		{
			Biome.Snow   => new Color( 0.40f, 0.60f, 0.95f, 0.13f ),
			Biome.Desert => new Color( 0.95f, 0.70f, 0.30f, 0.13f ),
			Biome.Swamp  => new Color( 0.40f, 0.75f, 0.35f, 0.13f ),
			_            => new Color( 0f, 0f, 0f, 0f ),
		};
	}

	/// <summary>Descriptive temperature label for the 0..1 BodyTemp axis.</summary>
	private static string TempLabelFor( float t )
	{
		if ( t <= 0.10f ) return "Freezing";
		if ( t <= 0.35f ) return "Cold";
		if ( t <= 0.65f ) return "Comfortable";
		if ( t <= 0.85f ) return "Hot";
		return "Burning";
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Public gameplay API — call these from anywhere.
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>Subtract <paramref name="amount"/> from Health and pulse the red damage overlay.</summary>
	public void TakeDamage( float amount )
	{
		if ( amount <= 0f ) return;
		Health = MathX.Clamp( Health - amount, 0f, MaxHealth );
		_timeSinceDamage = 0f;
		if ( !_flashVisible )
		{
			_flashVisible = true;
			Hud.DamageFlashVisible = true;
		}
		PushAll();
	}

	/// <summary>Add <paramref name="amount"/> to Health, clamped at MaxHealth.</summary>
	public void Heal( float amount )
	{
		if ( amount <= 0f ) return;
		Health = MathX.Clamp( Health + amount, 0f, MaxHealth );
		PushAll();
	}

	/// <summary>Add <paramref name="amount"/> to Hunger (eat food), clamped at MaxHunger.</summary>
	public void Eat( float amount )
	{
		if ( amount <= 0f ) return;
		Hunger = MathX.Clamp( Hunger + amount, 0f, MaxHunger );
		PushAll();
	}

	/// <summary>Add <paramref name="amount"/> to Thirst (drink water), clamped at MaxThirst.</summary>
	public void Drink( float amount )
	{
		if ( amount <= 0f ) return;
		Thirst = MathX.Clamp( Thirst + amount, 0f, MaxThirst );
		PushAll();
	}

	/// <summary>Add <paramref name="amount"/> to Stamina (rest), clamped at MaxStamina.</summary>
	public void Rest( float amount )
	{
		if ( amount <= 0f ) return;
		Stamina = MathX.Clamp( Stamina + amount, 0f, MaxStamina );
		PushAll();
	}

	/// <summary>Shift body temperature by <paramref name="delta"/> (positive = warmer).</summary>
	public void AdjustTemperature( float delta )
	{
		BodyTemp = MathX.Clamp( BodyTemp + delta, 0f, 1f );
		PushAll();
	}
}
