using Sandbox;
using SboxUiDesigner.Runtime;
using System;

namespace Sandbox.Samples;

/// <summary>
/// Companion <see cref="Component"/> for the <c>loadout_selector</c> showcase sample.
///
/// <para>Drop this on any GameObject, press <b>Play</b>, and a four-class
/// loadout picker appears centered on the screen. Click any of the four class
/// cards (ASSAULT / MEDIC / SNIPER / ENGINEER) to preview its name,
/// description, and four stat bars (Health / Speed / Damage / Range) in the
/// detail panel on the right. Click <b>Confirm Loadout</b> to commit the
/// selection — the controller raises <see cref="OnClassConfirmed"/> with the
/// chosen class id and hides the HUD so gameplay can take over.</para>
///
/// <para>The class roster lives in a single hardcoded
/// <see cref="ClassProfile"/> array near the top of this file. Edit the array
/// to swap classes — the four card buttons in the .sui are wired by index
/// (Assault=0, Medic=1, Sniper=2, Engineer=3) and the per-card click handlers
/// just call <see cref="PushSelectedToHud"/> after flipping
/// <see cref="_selected"/>.</para>
///
/// <para>The wrapper class <c>LoadoutSelector</c> is generated by the SUI
/// Designer from <c>loadout_selector.sui</c> on first compile, into
/// <c>Code/Samples/LoadoutSelector/</c> under the namespace
/// <c>Sandbox.Samples</c>.</para>
/// </summary>
public sealed class LoadoutSelectorController : Component
{
	/// <summary>
	/// POCO describing a single selectable class. Stats are normalized [0..1]
	/// fractions — the .sui's stat bars read them directly as ProgressBar Value.
	/// </summary>
	public sealed class ClassProfile
	{
		public string Name { get; set; } = "";
		public string Description { get; set; } = "";
		public float Health { get; set; }
		public float Speed { get; set; }
		public float Damage { get; set; }
		public float Range { get; set; }
	}

	// Hardcoded four-class roster. Order matters: the per-card click handlers
	// below match the .sui's ClassCard_1..ClassCard_4 in this exact order.
	// To change a class, edit a row here and update the corresponding
	// HoverStyle / BackgroundColor on the matching card in the .sui.
	private static readonly ClassProfile[] Profiles = new[]
	{
		new ClassProfile { Name = "ASSAULT",  Description = "Versatile front-line operator. Balanced stats with strong sustain fire.", Health = 0.70f, Speed = 0.70f, Damage = 0.70f, Range = 0.50f },
		new ClassProfile { Name = "MEDIC",    Description = "Support specialist. High health regen, moderate damage.",                  Health = 0.85f, Speed = 0.60f, Damage = 0.45f, Range = 0.40f },
		new ClassProfile { Name = "SNIPER",   Description = "Long-range eliminator. Glass cannon with extreme range.",                   Health = 0.45f, Speed = 0.55f, Damage = 0.95f, Range = 1.00f },
		new ClassProfile { Name = "ENGINEER", Description = "Battlefield builder. Deploys turrets and barriers.",                        Health = 0.60f, Speed = 0.50f, Damage = 0.55f, Range = 0.65f },
	};

	/// <summary>The generated UI wrapper. Exposed so you can inspect it in the inspector.</summary>
	[Property] public LoadoutSelector Hud { get; set; } = new();

	/// <summary>
	/// Raised when the player presses Confirm Loadout. Subscribers receive the
	/// selected class Name (e.g. "ASSAULT"). The controller hides the HUD
	/// immediately after invoking this — re-call <c>Hud.Show(...)</c> to
	/// re-open the picker if the player needs to change loadouts mid-match.
	/// </summary>
	public Action<string> OnClassConfirmed;

	// Currently-previewed class name. Defaults to "ASSAULT" to match the .sui's
	// initial Variable defaults so the panel renders consistently on frame zero
	// (before any click has run through PushSelectedToHud).
	private string _selected = "ASSAULT";

	// ─────────────────────────────────────────────────────────────────────────
	// Lifecycle.
	// ─────────────────────────────────────────────────────────────────────────

	protected override void OnStart()
	{
		// CRITICAL: assign every Code-mode delegate BEFORE Show(). The wrapper
		// hands these pointers to the renderer Panel inside SyncFieldsTo, which
		// runs as part of Show(). Assign-after-Show leaves the renderer with
		// null delegates and the clicks silently no-op forever. Same pitfall
		// the counter_button sample documents at length.
		Hud.OnAssaultClick = OnAssaultClick;
		Hud.OnMedicClick = OnMedicClick;
		Hud.OnSniperClick = OnSniperClick;
		Hud.OnEngineerClick = OnEngineerClick;
		Hud.OnConfirmClick = OnConfirmClick;

		// MouseOnly: the picker needs click input but shouldn't steal keyboard
		// focus from the rest of the game (chat, console, etc.).
		Hud.Show( GameObject, SuiInputMode.MouseOnly );

		// Seed the detail panel with the default class so the cold-start state
		// matches the card the player will most likely click first.
		PushSelectedToHud();
	}

	protected override void OnDestroy()
	{
		Hud?.Remove();
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Per-card click handlers. Each just flips _selected and re-syncs the
	// detail panel. The handler names below MUST match the Handler strings in
	// the .sui Events block exactly — the wrapper's SyncFieldsTo wires them
	// by reference equality on the delegate field name.
	// ─────────────────────────────────────────────────────────────────────────

	private void OnAssaultClick()
	{
		_selected = "ASSAULT";
		PushSelectedToHud();
	}

	private void OnMedicClick()
	{
		_selected = "MEDIC";
		PushSelectedToHud();
	}

	private void OnSniperClick()
	{
		_selected = "SNIPER";
		PushSelectedToHud();
	}

	private void OnEngineerClick()
	{
		_selected = "ENGINEER";
		PushSelectedToHud();
	}

	private void OnConfirmClick()
	{
		OnClassConfirmed?.Invoke( _selected );
		Log.Info( "Loadout confirmed: " + _selected );
		Hud.Hide();
	}

	// ─────────────────────────────────────────────────────────────────────────
	// State sync. Finds the profile matching _selected and writes the six
	// Variables in one shot. If _selected somehow falls off the roster (shouldn't
	// happen via the click handlers but defensive against future edits), we
	// fall back to the first profile rather than rendering an empty panel.
	// ─────────────────────────────────────────────────────────────────────────

	private void PushSelectedToHud()
	{
		ClassProfile profile = null;
		for ( var i = 0; i < Profiles.Length; i++ )
		{
			if ( Profiles[i].Name == _selected )
			{
				profile = Profiles[i];
				break;
			}
		}
		if ( profile == null && Profiles.Length > 0 )
		{
			profile = Profiles[0];
			_selected = profile.Name;
		}
		if ( profile == null ) return;

		Hud.SelectedClassName = profile.Name;
		Hud.SelectedClassDescription = profile.Description;
		Hud.HealthStatFraction = profile.Health;
		Hud.SpeedStatFraction = profile.Speed;
		Hud.DamageStatFraction = profile.Damage;
		Hud.RangeStatFraction = profile.Range;
	}
}
