using Sandbox;
using SboxUiDesigner.Runtime;

namespace Sandbox.Samples;

/// <summary>
/// Companion Component for the <c>death_respawn_modal</c> showcase sample - a
/// full-screen "you died" modal with cause-of-death blurb, an end-of-life
/// stats card (kills / time alive / distance traveled), a live respawn
/// countdown, and a primary <c>RESPAWN</c> + secondary <c>Spectate</c> action
/// pair.
///
/// <para>Drop this on a GameObject in any scene, press Play, and the modal
/// will appear immediately with a 3-second countdown. While the countdown is
/// running the primary button reads <c>"Waiting (Ns)..."</c> and clicking it
/// is a silent no-op; once the countdown hits 0 the button label flips to
/// <c>"RESPAWN"</c> and the click actually fires. The Spectate button is
/// always clickable.</para>
///
/// <para>Hotkey: press <c>K</c> (the default <c>Kill</c> action in s&amp;box's
/// input layout, falling back to <c>Score</c> = Tab on layouts that lack
/// Kill) to re-trigger the modal at any time — useful for iterating on
/// visuals without dying in actual gameplay.</para>
///
/// <para>The wrapper class <c>DeathRespawnModal</c> is generated by the SUI
/// Designer from <c>death_respawn_modal.sui</c> on first compile, into
/// <c>Code/Samples/DeathRespawnModal/</c> under the namespace
/// <c>Sandbox.Samples</c>.</para>
/// </summary>
public sealed class DeathRespawnModalController : Component
{
	// ─────────────────────────────────────────────────────────────────────────
	// Public properties — exposed in the Inspector and tweakable at runtime.
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>The generated UI wrapper. Exposed so you can tweak it in the inspector if needed.</summary>
	[Property] public DeathRespawnModal Hud { get; set; } = new();

	/// <summary>How long the respawn countdown runs before the button becomes clickable, in seconds.</summary>
	[Property, Range( 0f, 30f ), Group( "Countdown" )] public float RespawnDelaySeconds { get; set; } = 3f;

	/// <summary>Cause-of-death blurb shown under the YOU DIED headline. Set from gameplay code via <see cref="Show(string,int,float,float)"/>.</summary>
	[Property, Group( "Stats" )] public string DeathCause { get; set; } = "Killed by Unknown";

	/// <summary>Number of kills the player scored during this life. Display-only.</summary>
	[Property, Range( 0, 999 ), Group( "Stats" )] public int KillsThisLife { get; set; } = 0;

	/// <summary>How long the player survived this life, in seconds. Formatted as "Mm Ss".</summary>
	[Property, Range( 0f, 99999f ), Group( "Stats" )] public float TimeAliveSeconds { get; set; } = 0f;

	/// <summary>Total distance traveled this life, in source units. Formatted as "Xm".</summary>
	[Property, Range( 0f, 999999f ), Group( "Stats" )] public float DistanceTraveled { get; set; } = 0f;

	/// <summary>When true the modal is open; the countdown is running and the buttons are mounted.</summary>
	[Property, Group( "State" )] public bool IsOpen { get; set; } = true;

	// ─────────────────────────────────────────────────────────────────────────
	// Private state.
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>Seconds remaining on the respawn countdown. Counts down to 0 in <see cref="OnUpdate"/>.</summary>
	private float _countdownRemaining;

	/// <summary>True once the countdown hits 0 — gates the OnRespawnClick handler.</summary>
	private bool _canRespawn;

	/// <summary>Cached last value of <see cref="IsOpen"/> so we react to inspector toggles.</summary>
	private bool _wasOpen;

	// ─────────────────────────────────────────────────────────────────────────
	// Lifecycle.
	// ─────────────────────────────────────────────────────────────────────────

	protected override void OnStart()
	{
		// CRITICAL: assign every Code-mode delegate BEFORE Show(). The wrapper
		// hands these pointers to the renderer Panel inside SyncFieldsTo, which
		// runs as part of Show(). Assign-after-Show leaves the renderer with
		// null delegates and the clicks silently no-op forever. Same pitfall
		// the counter_button sample documents at length.
		Hud.OnRespawnClick = OnRespawnClick;
		Hud.OnSpectateClick = OnSpectateClick;

		// MouseOnly: the modal needs click input but we don't want to grab
		// keyboard focus from the rest of the game (chat, console, etc.).
		Hud.Show( GameObject, SuiInputMode.MouseOnly );

		_wasOpen = IsOpen;
		ResetCountdown();
		PushAll();
	}

	protected override void OnUpdate()
	{
		// Detect inspector toggle on IsOpen — open/close the modal accordingly.
		if ( IsOpen != _wasOpen )
		{
			_wasOpen = IsOpen;
			if ( IsOpen )
			{
				ResetCountdown();
			}
			// Note: we don't tear down the SuiPanel here — the modal stays
			// mounted but the controller just stops updating its state. For
			// a true hide, Hud.Remove() and re-Show() in OnStart-pattern.
		}

		// Hotkey to re-trigger the modal — useful for iterating on visuals.
		// "Kill" is the default suicide action in s&box's input layout; if a
		// project hasn't mapped it, Input.Pressed silently returns false and
		// nothing happens. Score (Tab) is the cross-layout fallback.
		if ( Input.Pressed( "Kill" ) || Input.Pressed( "Score" ) )
		{
			Show( DeathCause, KillsThisLife, TimeAliveSeconds, DistanceTraveled );
		}

		if ( !IsOpen )
			return;

		// Tick the countdown.
		if ( _countdownRemaining > 0f )
		{
			_countdownRemaining = MathX.Clamp( _countdownRemaining - Time.Delta, 0f, RespawnDelaySeconds );
			if ( _countdownRemaining <= 0f )
			{
				_canRespawn = true;
			}
		}

		PushAll();
	}

	protected override void OnDestroy()
	{
		Hud?.Remove();
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Push helpers.
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>Push every stat + countdown string into the SUI Variables in one shot.</summary>
	private void PushAll()
	{
		Hud.DeathCauseText = DeathCause;
		Hud.KillsThisLifeText = KillsThisLife.ToString();
		Hud.TimeAliveText = FormatTime( TimeAliveSeconds );
		Hud.DistanceText = FormatDistance( DistanceTraveled );

		if ( _canRespawn )
		{
			Hud.CountdownDisplayText = "Ready!";
			Hud.RespawnButtonText = "RESPAWN";
		}
		else
		{
			int secs = (int)System.Math.Ceiling( (double)_countdownRemaining );
			if ( secs < 1 ) secs = 1;
			Hud.CountdownDisplayText = $"Respawn in {secs}...";
			Hud.RespawnButtonText = $"Waiting ({secs})...";
		}
	}

	private void ResetCountdown()
	{
		_countdownRemaining = MathX.Clamp( RespawnDelaySeconds, 0f, 30f );
		_canRespawn = _countdownRemaining <= 0f;
	}

	/// <summary>"Mm Ss" formatter — no leading zeros on minutes, always two seconds digits when minutes > 0.</summary>
	private static string FormatTime( float seconds )
	{
		if ( seconds < 0f ) seconds = 0f;
		int total = (int)seconds;
		int m = total / 60;
		int s = total % 60;
		return $"{m}m {s}s";
	}

	/// <summary>"Xm" formatter — converts s&amp;box source units to meters (39.37 units per metre).</summary>
	private static string FormatDistance( float units )
	{
		if ( units < 0f ) units = 0f;
		int metres = (int)(units / 39.37f);
		return $"{metres}m";
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Event handlers — assigned to Hud.OnXxxClick in OnStart, fired by the
	// renderer Panel when the user clicks.
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>Click handler on the primary RESPAWN button. Silent no-op while the countdown is still running.</summary>
	private void OnRespawnClick()
	{
		if ( !_canRespawn )
			return;

		// Hook your real respawn here — e.g. respawn the pawn, fade out the
		// modal, fire an analytics event. The sample just closes the modal
		// and resets the countdown so you can hammer the hotkey to re-test.
		IsOpen = false;
		_wasOpen = false;
		Log.Info( "[DeathRespawnModal] Respawning player." );
	}

	/// <summary>Click handler on the secondary Spectate button.</summary>
	private void OnSpectateClick()
	{
		// Hook your real spectator-cam swap here. The sample just logs and
		// leaves the modal open so the user can still hit RESPAWN later.
		Log.Info( "[DeathRespawnModal] Switching to spectator mode." );
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Public gameplay API — call these from your damage / kill code.
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>
	/// Open the modal with fresh stats and restart the respawn countdown.
	/// Call this from your damage code when the player dies.
	/// </summary>
	/// <param name="cause">Cause-of-death blurb, e.g. "Killed by Player47" or "Fell to your death".</param>
	/// <param name="kills">Kill count for this life (display-only).</param>
	/// <param name="timeAliveSeconds">Seconds the player survived.</param>
	/// <param name="distanceTraveled">Distance traveled this life, in source units.</param>
	public void Show( string cause, int kills, float timeAliveSeconds, float distanceTraveled )
	{
		DeathCause = string.IsNullOrWhiteSpace( cause ) ? "Killed by Unknown" : cause;
		KillsThisLife = kills < 0 ? 0 : kills;
		TimeAliveSeconds = timeAliveSeconds < 0f ? 0f : timeAliveSeconds;
		DistanceTraveled = distanceTraveled < 0f ? 0f : distanceTraveled;
		IsOpen = true;
		_wasOpen = true;
		ResetCountdown();
		PushAll();
	}

	/// <summary>Close the modal without firing the respawn handler.</summary>
	public void Hide()
	{
		IsOpen = false;
		_wasOpen = false;
	}
}
