using Sandbox;
using SboxUiDesigner.Runtime;

namespace Sandbox.Samples;

/// <summary>
/// Companion <see cref="Component"/> for the <c>boss_hp_bar</c> showcase sample.
///
/// <para>Drop this on any GameObject, press <b>Play</b>, and a Dark-Souls style
/// boss bar appears centered at the top of the screen. The bar fill, the boss
/// name, and the phase label are all driven by SUI Variables — push values into
/// <see cref="Hud"/> from any gameplay code and the UI follows.</para>
///
/// <para>The white damage-flash overlay is the only element the controller
/// touches directly. It's exposed via <c>Hud.View?.DamageFlash</c> (the
/// generated @ref field on the renderer) and pulsed by writing
/// <c>Style.Opacity</c> on hit. Decays back to 0 over ~0.3s in
/// <see cref="OnUpdate"/>.</para>
///
/// <para><b>Hotkeys (built-in s&amp;box actions, universally mapped):</b></para>
/// <list type="bullet">
///   <item><b>Score</b> (default Tab) — deal 15% damage to the boss.</item>
///   <item><b>Reload</b> (default R) — heal 10% back.</item>
/// </list>
///
/// <para>The wrapper class <c>BossHpBar</c> is generated by the SUI Designer
/// from <c>boss_hp_bar.sui</c> on first compile, into
/// <c>Code/Samples/BossHpBar/</c> under the namespace <c>Sandbox.Samples</c>.</para>
/// </summary>
public sealed class BossHpBarController : Component
{
	/// <summary>The generated UI wrapper. Exposed so you can inspect it in the inspector.</summary>
	[Property] public BossHpBar Hud { get; set; } = new();

	/// <summary>Boss display name. Pushed (uppercased) into the BossName variable on Start.</summary>
	[Property] public string BossName { get; set; } = "Ancient Dragon";

	/// <summary>Current boss HP. Clamped to [0, MaxHp] every tick.</summary>
	[Property, Range( 0f, 99999f )] public float CurrentHp { get; set; } = 5000f;

	/// <summary>Maximum boss HP. Drives the normalization for HpFraction.</summary>
	[Property, Range( 1f, 99999f )] public float MaxHp { get; set; } = 5000f;

	/// <summary>How many phases the bar is divided into (matches the 3 tick marks → 4 phases).</summary>
	[Property, Range( 1, 16 )] public int Phases { get; set; } = 4;

	/// <summary>How much HP one Score press subtracts (as a fraction of MaxHp).</summary>
	[Property, Range( 0f, 1f )] public float DamagePerHit { get; set; } = 0.15f;

	/// <summary>How much HP one Reload press adds back (as a fraction of MaxHp).</summary>
	[Property, Range( 0f, 1f )] public float HealPerPress { get; set; } = 0.10f;

	/// <summary>Peak opacity the white overlay spikes to on hit.</summary>
	[Property, Range( 0f, 1f )] public float FlashPeak { get; set; } = 0.7f;

	/// <summary>Opacity decay per second after a hit.</summary>
	[Property, Range( 0.1f, 20f )] public float FlashDecayPerSecond { get; set; } = 3.5f;

	// Local cache of the current flash opacity. We can't rely on reading back
	// View.DamageFlash.Style.Opacity because Panel.Style values are nullable
	// floats; storing the truth here keeps the decay math tidy and survives
	// frames where the renderer hasn't mounted yet (View.DamageFlash null).
	private float _flashOpacity;

	protected override void OnStart()
	{
		// Passive mode — read-only HUD, never steals the cursor or keyboard focus.
		Hud.Show( SuiInputMode.Passive );

		// One-shot push: uppercase the name once on Start. Live edits to the
		// BossName property in the inspector won't re-uppercase mid-Play; that
		// is intentional (avoid string churn every tick).
		Hud.BossName = (BossName ?? string.Empty).ToUpperInvariant();

		PushToHud();
	}

	protected override void OnUpdate()
	{
		// Clamp once per tick — cheaper than guarding every external mutation.
		if ( MaxHp < 1f ) MaxHp = 1f;
		if ( CurrentHp < 0f ) CurrentHp = 0f;
		if ( CurrentHp > MaxHp ) CurrentHp = MaxHp;

		// Hotkeys for the showcase: Tab = damage, R = heal. These are the
		// "Score" and "Reload" built-in actions which ship mapped on every
		// fresh s&box install, so the sample works on day one with no input
		// config hand-editing.
		if ( Input.Pressed( "Score" ) )
		{
			TakeDamage( MaxHp * DamagePerHit );
		}
		if ( Input.Pressed( "Reload" ) )
		{
			Heal( MaxHp * HealPerPress );
		}

		// Decay the damage flash. We clamp to >= 0 so the value can't go
		// negative if Time.Delta spikes (e.g. editor pause).
		if ( _flashOpacity > 0f )
		{
			_flashOpacity = MathX.Clamp( _flashOpacity - Time.Delta * FlashDecayPerSecond, 0f, 1f );
			ApplyFlashOpacity();
		}

		PushToHud();
	}

	protected override void OnDestroy()
	{
		Hud?.Remove();
	}

	/// <summary>Push HP fraction + phase label into the SUI variables.</summary>
	private void PushToHud()
	{
		var frac = MaxHp > 0f ? CurrentHp / MaxHp : 0f;
		Hud.HpFraction = frac;

		// Phase math: divide [0..1] into <see cref="Phases"/> equal slices.
		// At full HP we're in the first phase ("Phase 1/4"); at 0 HP we're
		// in the last. Integer ceiling via (a + b - 1) / b avoids any
		// MathF dependency and is exact for our normalized inputs.
		var phasesSafe = Phases < 1 ? 1 : Phases;
		// remainingSlots in 0..phasesSafe ; ceil( frac * phasesSafe ).
		var scaled = frac * phasesSafe;
		var remaining = (int)scaled;
		if ( scaled - remaining > 0f ) remaining += 1;
		if ( remaining < 1 ) remaining = 1;
		if ( remaining > phasesSafe ) remaining = phasesSafe;
		// Display counts up as HP drops: 1/4 at full HP, 4/4 at the death blow.
		var displayPhase = phasesSafe - remaining + 1;
		Hud.PhaseLabel = $"Phase {displayPhase}/{phasesSafe}";
	}

	/// <summary>Write the current cached opacity into the live renderer Panel, if it exists yet.</summary>
	private void ApplyFlashOpacity()
	{
		// View.DamageFlash is the auto-generated @ref field on the renderer
		// (because the .sui marked DamageFlash as ExposeAsVariable=true).
		// It's null until Razor has rendered the wrapper at least once, so
		// null-coalesce defensively on every frame.
		var flash = Hud.View?.DamageFlash;
		if ( flash == null ) return;
		flash.Style.Opacity = _flashOpacity;
	}

	/// <summary>Subtract <paramref name="amount"/> HP, pulse the white overlay.</summary>
	public void TakeDamage( float amount )
	{
		if ( amount <= 0f ) return;
		CurrentHp = MathX.Clamp( CurrentHp - amount, 0f, MaxHp );

		// Spike the flash to peak; it'll decay in OnUpdate.
		_flashOpacity = FlashPeak;
		ApplyFlashOpacity();

		PushToHud();
	}

	/// <summary>Add <paramref name="amount"/> HP back, clamped to MaxHp. No flash.</summary>
	public void Heal( float amount )
	{
		if ( amount <= 0f ) return;
		CurrentHp = MathX.Clamp( CurrentHp + amount, 0f, MaxHp );
		PushToHud();
	}
}
