using Sandbox;
using SboxUiDesigner.Runtime;

namespace Sandbox.Samples;

/// <summary>
/// Companion Component for the <c>health_bar</c> showcase sample.
///
/// <para>Drop this on a GameObject in the scene, hit Play, the HUD appears in the
/// top-left corner. The bar fill and the value text are both driven by SUI
/// Variables — modify <see cref="Health"/> from any gameplay code (or call
/// <see cref="TakeDamage"/> / <see cref="Heal"/>) and the UI follows.</para>
///
/// <para>The wrapper class <c>HealthBar</c> is generated by the SUI Designer
/// from <c>health_bar.sui</c> on first compile, into
/// <c>Code/Samples/HealthBar/</c> under the namespace <c>Sandbox.Samples</c>.</para>
/// </summary>
public sealed class HealthBarController : Component
{
	/// <summary>The generated UI wrapper. Exposed so you can tweak it in the inspector if needed.</summary>
	[Property] public HealthBar Hud { get; set; } = new();

	/// <summary>Current health. Clamped to [0, MaxHealth] every frame.</summary>
	[Property, Range( 0f, 999f )] public float Health { get; set; } = 100f;

	/// <summary>Maximum health. Drives the denominator in the label and the bar's normalization.</summary>
	[Property, Range( 1f, 999f )] public float MaxHealth { get; set; } = 100f;

	protected override void OnStart()
	{
		// Passive mode — read-only HUD, never steals the cursor.
		Hud.Show( SuiInputMode.Passive );
		PushToHud();
	}

	protected override void OnUpdate()
	{
		// Keep Health in range every tick — easier than guarding every external mutation.
		if ( MaxHealth < 1f ) MaxHealth = 1f;
		if ( Health < 0f ) Health = 0f;
		if ( Health > MaxHealth ) Health = MaxHealth;

		PushToHud();
	}

	protected override void OnDestroy()
	{
		Hud?.Remove();
	}

	/// <summary>Push current Health/MaxHealth into the SUI Variables.</summary>
	private void PushToHud()
	{
		Hud.HealthFraction = MaxHealth > 0f ? Health / MaxHealth : 0f;
		Hud.HealthLabel = $"{(int)Health} / {(int)MaxHealth}";
	}

	/// <summary>Subtract <paramref name="amount"/> from Health, clamped at 0.</summary>
	public void TakeDamage( float amount )
	{
		if ( amount <= 0f ) return;
		Health = MathX.Clamp( Health - amount, 0f, MaxHealth );
		PushToHud();
	}

	/// <summary>Add <paramref name="amount"/> to Health, clamped at MaxHealth.</summary>
	public void Heal( float amount )
	{
		if ( amount <= 0f ) return;
		Health = MathX.Clamp( Health + amount, 0f, MaxHealth );
		PushToHud();
	}
}
