using System.Collections.Generic;
using System.Text;
using SboxUiDesigner.Runtime;

namespace SboxUiDesigner.Generation;

/// <summary>
/// Per-<see cref="SuiOutputMode"/> bootstrap codegen. Emits the auxiliary C#
/// file that turns a generated PanelComponent into something the user can drop
/// on a prefab without further wiring (PRD 17 § 5 + PRD 22 § 4).
///
/// <para><b>Manual</b> — no aux file. The class itself is the entry point.</para>
/// <para><b>Singleton</b> — static <c>Show()</c> + <c>Hide()</c> factory (PRD 22 § 4.9).</para>
/// <para><b>PerLocalPlayer</b> — Spawner wrapper Component (PRD 22 § 4.5).
/// User drops the Spawner on the player prefab; at runtime on the local player
/// only, the Spawner creates a child GameObject + ScreenPanel + the
/// PanelComponent, forwarding any user-set [Property] values from itself to
/// the spawned instance. Idempotent across re-enable/hot-reload.</para>
/// </summary>
public static class SuiOutputModeEmitter
{
	/// <summary>
	/// Render the bootstrap C# file for the active Output.Mode. Returns null
	/// when the mode needs no extra file (Manual). The result is a fully
	/// compilable .cs ready for the writer to drop into the output folder.
	/// </summary>
	public static string Emit( SuiDocument doc )
	{
		if ( doc?.Output == null ) return null;
		var className = doc.Output.ClassName;
		var ns = doc.Output.Namespace ?? "Game.UI";
		if ( string.IsNullOrEmpty( className ) ) return null;

		switch ( doc.Output.Mode )
		{
			case SuiOutputMode.PerLocalPlayer:
				return EmitPerLocalPlayer( doc, ns, className );

			case SuiOutputMode.Singleton:
				return EmitSingleton( doc, ns, className );

			case SuiOutputMode.Manual:
			default:
				return null;
		}
	}

	/// <summary>Generated-file name used by the writer. Null for modes that produce no aux file.</summary>
	public static string EmitFileName( SuiDocument doc )
	{
		if ( doc?.Output == null ) return null;
		var className = doc.Output.ClassName;
		if ( string.IsNullOrEmpty( className ) ) return null;
		return doc.Output.Mode switch
		{
			SuiOutputMode.PerLocalPlayer => className + "Spawner.cs",
			SuiOutputMode.Singleton => className + "Factory.cs",
			_ => null,
		};
	}

	private static string EmitPerLocalPlayer( SuiDocument doc, string ns, string className )
	{
		var sb = new StringBuilder();
		sb.AppendLine( "// <auto-generated/>" );
		sb.AppendLine( "// SUI Designer V1.5 — PerLocalPlayer auto-mount Spawner (PRD 22 § 4.5)." );
		sb.AppendLine( "// Drop this Component on the player prefab. On the local player only," );
		sb.AppendLine( "// it spawns a child GameObject + ScreenPanel + the HUD PanelComponent." );
		sb.AppendLine( "// Re-generated on every compile; do not edit by hand." );
		sb.AppendLine();
		sb.AppendLine( "using Sandbox;" );
		sb.AppendLine( "using Sandbox.UI;" );
		sb.AppendLine();
		sb.AppendLine( $"namespace {ns};" );
		sb.AppendLine();
		sb.AppendLine( $"[Title( \"{className} (Spawner)\" )]" );
		sb.AppendLine( $"public sealed class {className}Spawner : Component" );
		sb.AppendLine( "{" );
		sb.AppendLine( "\t[Property] public bool AutoSpawnOnLocalPlayer { get; set; } = true;" );
		sb.AppendLine();
		sb.AppendLine( "\tprivate GameObject _screenPanelHost;" );
		sb.AppendLine( $"\tprivate {className} _instance;" );
		sb.AppendLine();

		// Forwarded properties: every Variable that emits as [Property] + every AcceptedProp.
		// Same accessors as the generated PanelComponent so the user can set them on the
		// Spawner in the inspector and have them propagate to the spawned instance.
		EmitForwardedProperties( doc, sb );

		sb.AppendLine();
		sb.AppendLine( "\tprotected override void OnEnabled()" );
		sb.AppendLine( "\t{" );
		sb.AppendLine( "\t\tbase.OnEnabled();" );
		sb.AppendLine( "\t\tif ( IsProxy || !AutoSpawnOnLocalPlayer ) return;" );
		sb.AppendLine( "\t\tif ( _screenPanelHost.IsValid() ) return;" );
		sb.AppendLine();
		sb.AppendLine( $"\t\t_screenPanelHost = new GameObject( true, \"{className}_Screen\" );" );
		sb.AppendLine( "\t\t_screenPanelHost.SetParent( GameObject );" );
		sb.AppendLine( "\t\t_screenPanelHost.Components.Create<ScreenPanel>();" );
		sb.AppendLine( $"\t\t_instance = _screenPanelHost.Components.Create<{className}>();" );
		sb.AppendLine();
		sb.AppendLine( "\t\tForwardProperties();" );
		sb.AppendLine( "\t}" );
		sb.AppendLine();
		sb.AppendLine( "\tprotected override void OnDisabled()" );
		sb.AppendLine( "\t{" );
		sb.AppendLine( "\t\tbase.OnDisabled();" );
		sb.AppendLine( "\t\t_screenPanelHost?.Destroy();" );
		sb.AppendLine( "\t\t_screenPanelHost = null;" );
		sb.AppendLine( "\t\t_instance = null;" );
		sb.AppendLine( "\t}" );
		sb.AppendLine();
		sb.AppendLine( "\tvoid ForwardProperties()" );
		sb.AppendLine( "\t{" );
		sb.AppendLine( "\t\tif ( !_instance.IsValid() ) return;" );
		EmitForwardAssignments( doc, sb );
		sb.AppendLine( "\t}" );
		sb.AppendLine( "}" );
		return sb.ToString();
	}

	private static string EmitSingleton( SuiDocument doc, string ns, string className )
	{
		var sb = new StringBuilder();
		sb.AppendLine( "// <auto-generated/>" );
		sb.AppendLine( "// SUI Designer V1.5 — Singleton factory (PRD 22 § 4.9)." );
		sb.AppendLine( $"// Use {className}.Show() to display, .Hide() on the returned instance to dismiss." );
		sb.AppendLine();
		sb.AppendLine( "using Sandbox;" );
		sb.AppendLine( "using Sandbox.UI;" );
		sb.AppendLine();
		sb.AppendLine( $"namespace {ns};" );
		sb.AppendLine();
		sb.AppendLine( $"public sealed partial class {className}" );
		sb.AppendLine( "{" );
		sb.AppendLine( $"\tpublic static {className} Show()" );
		sb.AppendLine( "\t{" );
		sb.AppendLine( "\t\tvar go = Game.ActiveScene.CreateObject();" );
		sb.AppendLine( $"\t\tgo.Name = \"{className}\";" );
		sb.AppendLine( "\t\tgo.Components.Create<ScreenPanel>();" );
		sb.AppendLine( $"\t\treturn go.Components.Create<{className}>();" );
		sb.AppendLine( "\t}" );
		sb.AppendLine();
		sb.AppendLine( "\tpublic void Hide() => GameObject?.Destroy();" );
		sb.AppendLine( "}" );
		return sb.ToString();
	}

	private static void EmitForwardedProperties( SuiDocument doc, StringBuilder sb )
	{
		// Plain [Property]s the Spawner needs to mirror — Manual Variables + AcceptedProps.
		// FromAcceptedProp aliases collapse into their AcceptedProp.

		if ( doc.AcceptedProps != null )
		{
			foreach ( var p in doc.AcceptedProps )
			{
				if ( p == null || string.IsNullOrEmpty( p.Name ) ) continue;
				var csType = SuiTypeMapper.ToCSharp( p.Type );
				var def = SuiTypeMapper.DefaultLiteral( p.Type, p.Default );
				sb.Append( "\t[Property, Group( \"" ).Append( p.Group ?? "Slot" ).Append( "\" )] public " )
					.Append( csType ).Append( ' ' ).Append( p.Name )
					.Append( " { get; set; } = " ).Append( def ).AppendLine( ";" );
			}
		}

		if ( doc.Variables != null )
		{
			foreach ( var v in doc.Variables )
			{
				if ( v == null || string.IsNullOrEmpty( v.Name ) ) continue;
				if ( (v.Source?.Kind ?? SuiVariableSourceKind.Manual) != SuiVariableSourceKind.Manual ) continue;
				var csType = SuiTypeMapper.ToCSharp( v.Type );
				var def = SuiTypeMapper.DefaultLiteral( v.Type, v.Default );
				sb.Append( "\t[Property" );
				if ( !string.IsNullOrEmpty( v.Group ) )
					sb.Append( ", Group( \"" ).Append( v.Group.Replace( "\"", "\\\"" ) ).Append( "\" )" );
				sb.Append( "] public " ).Append( csType ).Append( ' ' ).Append( v.Name )
					.Append( " { get; set; } = " ).Append( def ).AppendLine( ";" );
			}
		}
	}

	private static void EmitForwardAssignments( SuiDocument doc, StringBuilder sb )
	{
		if ( doc.AcceptedProps != null )
		{
			foreach ( var p in doc.AcceptedProps )
			{
				if ( p == null || string.IsNullOrEmpty( p.Name ) ) continue;
				sb.Append( "\t\t_instance." ).Append( p.Name ).Append( " = " ).Append( p.Name ).AppendLine( ";" );
			}
		}
		if ( doc.Variables != null )
		{
			foreach ( var v in doc.Variables )
			{
				if ( v == null || string.IsNullOrEmpty( v.Name ) ) continue;
				if ( (v.Source?.Kind ?? SuiVariableSourceKind.Manual) != SuiVariableSourceKind.Manual ) continue;
				sb.Append( "\t\t_instance." ).Append( v.Name ).Append( " = " ).Append( v.Name ).AppendLine( ";" );
			}
		}
	}
}
