using System.Collections.Generic;
using System.Text;
using SboxUiDesigner.Runtime;

namespace SboxUiDesigner.Generation;

/// <summary>
/// Per-<see cref="SuiOutputMode"/> bootstrap codegen. Emits the auxiliary C#
/// file that turns a generated PanelComponent into something the user can drop
/// on a prefab without further wiring (PRD 17 § 5 + PRD 22 § 4).
///
/// <para><b>Manual</b> — no aux file. The class itself is the entry point.</para>
/// <para><b>Singleton</b> — static <c>Show()</c> + <c>Hide()</c> factory (PRD 22 § 4.9).</para>
/// <para><b>PerLocalPlayer</b> — Spawner wrapper Component (PRD 22 § 4.5).
/// User drops the Spawner on the player prefab; at runtime on the local player
/// only, the Spawner creates a child GameObject + ScreenPanel + the
/// PanelComponent, forwarding any user-set [Property] values from itself to
/// the spawned instance. Idempotent across re-enable/hot-reload.</para>
/// </summary>
public static class SuiOutputModeEmitter
{
	/// <summary>
	/// Render the bootstrap C# file for the active Output.Mode. Returns null
	/// when the mode needs no extra file (Manual). The result is a fully
	/// compilable .cs ready for the writer to drop into the output folder.
	/// </summary>
	public static string Emit( SuiDocument doc, SuiGenerationContext ctx = null )
	{
		if ( doc?.Output == null ) return null;
		var className = doc.Output.ClassName;
		var ns = doc.Output.Namespace ?? "Game.UI";
		if ( string.IsNullOrEmpty( className ) ) return null;

#pragma warning disable CS0618
		var mode = doc.Output.Mode == SuiOutputMode.PerLocalPlayer
			? SuiOutputMode.Instance  // auto-migrate legacy mode to Instance
			: doc.Output.Mode;
#pragma warning restore CS0618

		switch ( mode )
		{
			case SuiOutputMode.Instance:
				return EmitInstance( doc, ns, className, ctx );

			case SuiOutputMode.Singleton:
				return EmitSingleton( doc, ns, className );

			case SuiOutputMode.Manual:
			default:
				return null;
		}
	}

	/// <summary>Generated-file name used by the writer. Null for modes that produce no aux file.</summary>
	public static string EmitFileName( SuiDocument doc )
	{
		if ( doc?.Output == null ) return null;
		var className = doc.Output.ClassName;
		if ( string.IsNullOrEmpty( className ) ) return null;
#pragma warning disable CS0618
		var mode = doc.Output.Mode == SuiOutputMode.PerLocalPlayer
			? SuiOutputMode.Instance
			: doc.Output.Mode;
#pragma warning restore CS0618
		return mode switch
		{
			SuiOutputMode.Instance => className + ".cs",
			SuiOutputMode.Singleton => className + "Factory.cs",
			_ => null,
		};
	}

	private static string EmitInstance( SuiDocument doc, string ns, string className, SuiGenerationContext ctx )
	{
		var sb = new StringBuilder();
		sb.AppendLine( "// <auto-generated/>" );
		sb.AppendLine( "// SUI Designer V1.5 — Instance-mode wrapper (PRD 19/22 revised)." );
		sb.AppendLine( "// Declare on your own Component as:" );
		sb.AppendLine( $"//     [Property] public {className} Widget {{ get; set; }} = new();" );
		sb.AppendLine( "// then drive it from gameplay code:" );
		sb.AppendLine( "//     Widget.Show();   // mount + visible" );
		sb.AppendLine( "//     Widget.Hide();   // hide, keep mount" );
		sb.AppendLine( "//     Widget.Remove(); // destroy mount" );
		sb.AppendLine( "// Re-generated on every compile; do not edit by hand." );
		sb.AppendLine();
		sb.AppendLine( "using Sandbox;" );
		sb.AppendLine( "using SboxUiDesigner.Runtime;" );
		sb.AppendLine();
		sb.AppendLine( $"namespace {ns};" );
		sb.AppendLine();
		sb.AppendLine( $"[Title( \"{className}\" )]" );
		sb.AppendLine( $"public sealed class {className} : SuiPanel<{className}Panel>" );
		sb.AppendLine( "{" );

		// Wrapper-side [Property] fields. Mirror every Manual Variable + every
		// SuiReference (M2-K4 named-instance). The Panel has IDENTICAL fields;
		// SyncFieldsTo passes each one by reference so user edits on the wrapper
		// (parent.StaminaBar.ActualValue = 75) flow into the live View on the
		// next render cycle.
		EmitForwardedProperties( doc, sb );
		EmitForwardedChildReferences( doc, ctx, sb );

		sb.AppendLine();
		sb.AppendLine( $"\tprotected override void SyncFieldsTo( {className}Panel view )" );
		sb.AppendLine( "\t{" );
		EmitForwardAssignmentsForView( doc, sb, "view" );
		EmitForwardChildAssignments( doc, ctx, sb, "view" );
		sb.AppendLine( "\t}" );
		sb.AppendLine( "}" );
		return sb.ToString();
	}

	private static void EmitForwardedChildReferences( SuiDocument doc, SuiGenerationContext ctx, StringBuilder sb )
	{
		if ( doc?.Elements == null || ctx?.ResolveReferencedClass == null ) return;
		foreach ( var el in doc.Elements )
		{
			if ( el?.Type != SuiElementType.SuiReference ) continue;
			var data = el.SuiReference;
			if ( data == null || string.IsNullOrEmpty( data.SourceGuid ) ) continue;
			var target = ctx.ResolveReferencedClass( data.SourceGuid );
			if ( target == null || string.IsNullOrEmpty( target.ClassName ) ) continue;

			var childWrapperType = string.IsNullOrEmpty( target.Namespace )
				? target.ClassName
				: $"{target.Namespace}.{target.ClassName}";
			var fieldName = SuiNameSanitizer.ToCSharpIdentifier( el.Name );
			if ( string.IsNullOrEmpty( fieldName ) ) continue;

			var isForEach = data.ForEach != null && !string.IsNullOrEmpty( data.ForEach.SourceVariableId );
			if ( isForEach )
			{
				sb.Append( "\t[Property, Group( \"Children\" )] public System.Collections.Generic.List<" )
					.Append( childWrapperType ).Append( "> " ).Append( fieldName )
					.AppendLine( " { get; set; } = new();" );
			}
			else
			{
				sb.Append( "\t[Property, Group( \"Children\" )] public " )
					.Append( childWrapperType ).Append( ' ' ).Append( fieldName )
					.Append( " { get; set; } = new " ).Append( childWrapperType ).AppendLine( "();" );
			}
		}
	}

	private static void EmitForwardChildAssignments( SuiDocument doc, SuiGenerationContext ctx, StringBuilder sb, string varName )
	{
		if ( doc?.Elements == null || ctx?.ResolveReferencedClass == null ) return;
		foreach ( var el in doc.Elements )
		{
			if ( el?.Type != SuiElementType.SuiReference ) continue;
			var data = el.SuiReference;
			if ( data == null || string.IsNullOrEmpty( data.SourceGuid ) ) continue;
			var target = ctx.ResolveReferencedClass( data.SourceGuid );
			if ( target == null || string.IsNullOrEmpty( target.ClassName ) ) continue;
			var fieldName = SuiNameSanitizer.ToCSharpIdentifier( el.Name );
			if ( string.IsNullOrEmpty( fieldName ) ) continue;

			sb.Append( "\t\t" ).Append( varName ).Append( '.' ).Append( fieldName )
				.Append( " = " ).Append( fieldName ).AppendLine( ";" );
		}
	}

	private static void EmitForwardAssignmentsForView( SuiDocument doc, StringBuilder sb, string varName )
	{
		// V1.5-M2-K — every Manual Variable forwards; IsPublic vs internal
		// both apply (the wrapper is the single source of truth feeding the
		// rendered View).
		if ( doc.Variables == null ) return;
		foreach ( var v in doc.Variables )
		{
			if ( v == null || string.IsNullOrEmpty( v.Name ) ) continue;
			if ( (v.Source?.Kind ?? SuiVariableSourceKind.Manual) != SuiVariableSourceKind.Manual ) continue;
			sb.Append( "\t\t" ).Append( varName ).Append( '.' ).Append( v.Name )
				.Append( " = " ).Append( v.Name ).AppendLine( ";" );
		}
	}

	private static string EmitSingleton( SuiDocument doc, string ns, string className )
	{
		var sb = new StringBuilder();
		sb.AppendLine( "// <auto-generated/>" );
		sb.AppendLine( "// SUI Designer V1.5 — Singleton factory (PRD 22 § 4.9)." );
		sb.AppendLine( $"// Use {className}.Show() to display, .Hide() on the returned instance to dismiss." );
		sb.AppendLine();
		sb.AppendLine( "using Sandbox;" );
		sb.AppendLine( "using Sandbox.UI;" );
		sb.AppendLine();
		sb.AppendLine( $"namespace {ns};" );
		sb.AppendLine();
		sb.AppendLine( $"public sealed partial class {className}" );
		sb.AppendLine( "{" );
		sb.AppendLine( $"\tpublic static {className} Show()" );
		sb.AppendLine( "\t{" );
		sb.AppendLine( "\t\tvar go = Game.ActiveScene.CreateObject();" );
		sb.AppendLine( $"\t\tgo.Name = \"{className}\";" );
		sb.AppendLine( "\t\tgo.Components.Create<ScreenPanel>();" );
		sb.AppendLine( $"\t\treturn go.Components.Create<{className}>();" );
		sb.AppendLine( "\t}" );
		sb.AppendLine();
		sb.AppendLine( "\tpublic void Hide() => GameObject?.Destroy();" );
		sb.AppendLine( "}" );
		return sb.ToString();
	}

	private static void EmitForwardedProperties( SuiDocument doc, StringBuilder sb )
	{
		// V1.5-M2-K — every Manual Variable becomes a [Property] on the wrapper.
		// IsPublic Variables get an extra hint in the inspector group so the
		// user sees which fields are also surfaced to parent embeds.
		if ( doc.Variables == null ) return;
		foreach ( var v in doc.Variables )
		{
			if ( v == null || string.IsNullOrEmpty( v.Name ) ) continue;
			if ( (v.Source?.Kind ?? SuiVariableSourceKind.Manual) != SuiVariableSourceKind.Manual ) continue;

			var csType = SuiTypeMapper.ToCSharp( v.Type );
			var def = SuiTypeMapper.DefaultLiteral( v.Type, v.Default );
			var group = v.Group ?? ( v.IsPublic ? "Public" : "Internal" );

			sb.Append( "\t[Property, Group( \"" ).Append( group.Replace( "\"", "\\\"" ) ).Append( "\" )] public " )
				.Append( csType ).Append( ' ' ).Append( v.Name )
				.Append( " { get; set; } = " ).Append( def ).AppendLine( ";" );
		}
	}

	// Old _instance.* forwarder was removed alongside the PerLocalPlayer
	// Spawner pattern — Instance mode uses EmitForwardAssignmentsForView.
}
