using System.Text;
using SboxUiDesigner.Runtime;

namespace SboxUiDesigner.Generation;

/// <summary>
/// V1.5-M2-K6 — every <c>.sui</c> compile generates a user-facing wrapper
/// class alongside the <c>PanelComponent</c> renderer. One concept, one
/// generated shape, no per-document mode toggle (DEVIATIONS D-013).
///
/// <para>The wrapper class extends <c>SuiPanel&lt;TPanel&gt;</c> (see
/// <c>Code/Runtime/SuiPanel.cs</c>) and provides:
/// <list type="bullet">
///   <item><c>Add()/Show()/Hide()/Remove()</c> — lifetime control.</item>
///   <item>A <c>[Property]</c> field per Manual Variable, mirroring values
///         straight into the live View on <c>SyncFieldsTo</c>.</item>
///   <item>A named-instance <c>[Property]</c> field per <c>SuiReference</c>
///         element on the parent canvas (single instance or
///         <c>List&lt;TChild&gt;</c> when ForEach is enabled), so user code
///         can do <c>parent.ChildName.Var = ...</c>.</item>
/// </list></para>
///
/// <para>The dev declares the wrapper as a <c>[Property]</c> field on their
/// own Component:
/// <code>
///   [Property] public WdgSelectJob Widget { get; set; } = new();
///   void Update() { Widget.Show(); Widget.StaminaRow.StatValue = "75"; }
/// </code></para>
/// </summary>
public static class SuiWrapperEmitter
{
	public static string Emit( SuiDocument doc, SuiGenerationContext ctx = null )
	{
		if ( doc?.Output == null ) return null;

		// Use the sanitized wrapper name the pipeline already produced — falls
		// back to a fresh sanitize of the raw Output.ClassName when ctx is null
		// (called outside the normal pipeline). Without this, names with
		// hyphens / underscores / spaces leak straight into C# and fail.
		var className = !string.IsNullOrEmpty( ctx?.WrapperClassName )
			? ctx.WrapperClassName
			: SuiNameSanitizer.ToCSharpIdentifier( doc.Output.ClassName );
		var ns = doc.Output.Namespace ?? "Game.UI";
		if ( string.IsNullOrEmpty( className ) ) return null;

		var sb = new StringBuilder();
		// SUI ownership header — lets the compile step recognize this file as
		// generated by THIS .sui and safely overwrite it on next compile.
		sb.Append( SuiHeaderEmitter.EmitCsHeader( doc ) );
		sb.AppendLine( "//" );
		sb.AppendLine( "// Wrapper class for the generated PanelComponent. Declare on any Component as:" );
		sb.AppendLine( $"//     [Property] public {className} Widget {{ get; set; }} = new();" );
		sb.AppendLine( "// then drive it from gameplay code:" );
		sb.AppendLine( "//     Widget.Show();                       // mount + visible" );
		sb.AppendLine( "//     Widget.Hide();                       // hide, keep mount" );
		sb.AppendLine( "//     Widget.Remove();                     // destroy mount" );
		sb.AppendLine( "//     Widget.SomeVar = 42;                 // edit a public Variable" );
		sb.AppendLine( "//     Widget.ChildName.NestedVar = \"x\";  // address a SuiReference by name" );
		sb.AppendLine();
		sb.AppendLine( "using System;" );
		sb.AppendLine( "using Sandbox;" );
		sb.AppendLine( "using SboxUiDesigner.Runtime;" );
		sb.AppendLine();
		sb.AppendLine( $"namespace {ns};" );
		sb.AppendLine();
		sb.AppendLine( $"[Title( \"{className}\" )]" );
		sb.AppendLine( $"public sealed class {className} : SuiPanel<{className}Panel>" );
		sb.AppendLine( "{" );

		// Wrapper fields mirror the panel's fields — same names, same types.
		// SyncFieldsTo passes them down by reference so user edits on the
		// wrapper flow into the live view automatically on next render.
		EmitVariableProperties( doc, sb );
		EmitChildReferenceProperties( doc, ctx, sb );
		// V1.5 M3 — Code-mode event slots become wrapper [Property] Action
		// fields that the user assigns (typically via the .partial.cs handler
		// reference). Doo mode lands in Phase 3.
		SuiEventEmitter.EmitWrapperProperties( doc, sb );
		// V1.5 M4 — input widget bind mirrors were removed in favour of
		// unified Variable bindings (Bindings tab → "Value" / "Checked" on
		// the widget targets a doc Variable). Variables already produce
		// public wrapper properties via EmitVariableProperties, so any input
		// widget bound to a Variable is reachable as `widget.<VarName>`.

		sb.AppendLine();
		sb.AppendLine( $"\tprotected override void SyncFieldsTo( {className}Panel view )" );
		sb.AppendLine( "\t{" );
		EmitVariableAssignments( doc, sb, "view" );
		EmitChildReferenceAssignments( doc, ctx, sb, "view" );
		SuiEventEmitter.EmitWrapperSyncAssignments( doc, sb, "view" );
		sb.AppendLine( "\t}" );

		// V1.5 — explicit commit methods for bindings with UpdateTrigger=Manual.
		// User code calls `wrapper.Commit<Name>()` to push the current widget
		// state into the bound Variable (e.g. from a Save button click).
		EmitManualCommitMethods( doc, sb );

		// V1.5-M2-K7-bugfix — recursive content hash. Without this, mutating a
		// grandchild Variable doesn't change the grandparent Razor's BuildHash
		// (the grandparent only sees its direct child's PublicVariables — the
		// inner ones are invisible). Each wrapper hashes its own Manual
		// Variables plus the recursive ContentHash() of every child wrapper.
		EmitContentHash( doc, ctx, sb );

		sb.AppendLine( "}" );
		return sb.ToString();
	}

	/// <summary>Generated-file name used by the writer. Always <c>&lt;ClassName&gt;.cs</c> in M2-K6.</summary>
	public static string EmitFileName( SuiDocument doc )
	{
		var className = doc?.Output?.ClassName;
		if ( string.IsNullOrEmpty( className ) ) return null;
		// Match what Emit() actually writes — sanitized identifier, not the raw input.
		return SuiNameSanitizer.ToCSharpIdentifier( className ) + ".cs";
	}

	// ─────────────────────────────────────────────────────────────────────
	//  Variables (per Manual SuiVariable in the doc)
	// ─────────────────────────────────────────────────────────────────────

	private static void EmitVariableProperties( SuiDocument doc, StringBuilder sb )
	{
		if ( doc.Variables == null ) return;
		foreach ( var v in doc.Variables )
		{
			if ( v == null || string.IsNullOrEmpty( v.Name ) ) continue;

			var csType = SuiTypeMapper.ToCSharp( v.Type );
			var def = SuiTypeMapper.DefaultLiteral( v.Type, v.Default );
			var group = v.Group ?? ( v.IsPublic ? "Public" : "Internal" );
			var backing = "_" + char.ToLowerInvariant( v.Name[0] ) + v.Name.Substring( 1 );

			// Backing field + property:
			//
			//   get — reads from the live View when mounted so two-way `:bind`
			//         updates flow back automatically (M4). For one-way
			//         bindings View.X mirrors the backing, so reading either
			//         side gives the same answer — the View-first form is
			//         correct for ALL modes.
			//
			//   set — writes the backing AND pushes into the View so the
			//         renderer's BuildHash() sees the change and re-renders.
			//         SyncFieldsTo handles the cold-start path on mount.
			sb.Append( "\tprivate " ).Append( csType ).Append( ' ' ).Append( backing )
				.Append( " = " ).Append( def ).AppendLine( ";" );

			sb.Append( "\t[Property, Group( \"" ).Append( group.Replace( "\"", "\\\"" ) ).Append( "\" )] public " )
				.Append( csType ).Append( ' ' ).Append( v.Name ).AppendLine();
			sb.AppendLine( "\t{" );
			sb.Append( "\t\tget => View != null ? View." ).Append( v.Name )
				.Append( " : " ).Append( backing ).AppendLine( ";" );
			sb.AppendLine( "\t\tset" );
			sb.AppendLine( "\t\t{" );
			sb.Append( "\t\t\t" ).Append( backing ).AppendLine( " = value;" );
			sb.Append( "\t\t\tif ( View != null ) View." ).Append( v.Name ).AppendLine( " = value;" );
			sb.AppendLine( "\t\t}" );
			sb.AppendLine( "\t}" );
		}
	}

	private static void EmitVariableAssignments( SuiDocument doc, StringBuilder sb, string varName )
	{
		if ( doc.Variables == null ) return;
		foreach ( var v in doc.Variables )
		{
			if ( v == null || string.IsNullOrEmpty( v.Name ) ) continue;
			sb.Append( "\t\t" ).Append( varName ).Append( '.' ).Append( v.Name )
				.Append( " = " ).Append( v.Name ).AppendLine( ";" );
		}
	}

	// ─────────────────────────────────────────────────────────────────────
	//  Named-instance child references (per SuiReference element)
	// ─────────────────────────────────────────────────────────────────────

	private static void EmitChildReferenceProperties( SuiDocument doc, SuiGenerationContext ctx, StringBuilder sb )
	{
		if ( doc?.Elements == null || ctx?.ResolveReferencedClass == null ) return;
		foreach ( var el in doc.Elements )
		{
			if ( el?.Type != SuiElementType.SuiReference ) continue;
			var data = el.SuiReference;
			if ( data == null || string.IsNullOrEmpty( data.SourceGuid ) ) continue;
			var target = ctx.ResolveReferencedClass( data.SourceGuid );
			if ( target == null || string.IsNullOrEmpty( target.ClassName ) ) continue;

			// global:: prefix avoids namespace collisions when the parent
			// namespace contains a prefix of the child's.
			var childWrapperType = string.IsNullOrEmpty( target.Namespace )
				? target.ClassName
				: $"global::{target.Namespace}.{target.ClassName}";
			var fieldName = SuiNameSanitizer.ToCSharpIdentifier( el.Name );
			if ( string.IsNullOrEmpty( fieldName ) ) continue;

			var isForEach = data.ForEach != null && !string.IsNullOrEmpty( data.ForEach.SourceVariableId );
			if ( isForEach )
			{
				sb.Append( "\t[Property, Group( \"Children\" )] public System.Collections.Generic.List<" )
					.Append( childWrapperType ).Append( "> " ).Append( fieldName )
					.AppendLine( " { get; set; } = new();" );
			}
			else
			{
				sb.Append( "\t[Property, Group( \"Children\" )] public " )
					.Append( childWrapperType ).Append( ' ' ).Append( fieldName )
					.Append( " { get; set; } = new " ).Append( childWrapperType ).AppendLine( "();" );
			}
		}
	}

	// ─────────────────────────────────────────────────────────────────────
	//  Input widget bind mirrors (V1.5 M4)
	// ─────────────────────────────────────────────────────────────────────
	//
	// For TextEntry / Checkbox / DropDown / Slider the wrapper mirrors the
	// panel's bind field as a `[Property]` with auto-push semantics:
	//   * `get` reads from the live View when mounted so the latest
	//     user-edited value comes back, falling back to the backing field
	//     when the wrapper isn't yet mounted.
	//   * `set` writes to the backing field AND to the View, so user code
	//     that pre-fills `widget.NameEntryValue = "x"` before Show() picks
	//     the right initial value AND mutations after Show() take effect
	//     without manual RefreshView.
	// Matches the existing Variable pattern (see EmitVariableProperties).

	private struct InputBindSpec
	{
		public string FieldName;     // matches panel field, e.g. "NameEntryValue"
		public string CsType;        // "string" | "bool" | "int" | "float"
		public string BackingName;   // "_nameEntryValue"
		public string DefaultLit;    // initial literal
	}

	private static System.Collections.Generic.IEnumerable<InputBindSpec> CollectInputBinds( SuiDocument doc )
	{
		if ( doc?.Elements == null ) yield break;
		var inv = System.Globalization.CultureInfo.InvariantCulture;

		foreach ( var el in doc.Elements )
		{
			if ( el == null ) continue;
			var baseName = el.Name ?? el.Id;
			if ( string.IsNullOrEmpty( baseName ) ) continue;

			switch ( el.Type )
			{
				case SuiElementType.TextEntry:
					{
						var name = SuiNameSanitizer.ToCSharpIdentifier( baseName + "Value" );
						if ( string.IsNullOrEmpty( name ) ) break;
						var def = el.Props?.PreviewValue ?? "";
						yield return new InputBindSpec
						{
							FieldName = name,
							CsType = "string",
							BackingName = "_" + char.ToLowerInvariant( name[0] ) + name.Substring( 1 ),
							DefaultLit = "\"" + def.Replace( "\\", "\\\\" ).Replace( "\"", "\\\"" ) + "\"",
						};
					}
					break;

				case SuiElementType.Toggle:
					{
						var name = SuiNameSanitizer.ToCSharpIdentifier( baseName + "Checked" );
						if ( string.IsNullOrEmpty( name ) ) break;
						yield return new InputBindSpec
						{
							FieldName = name,
							CsType = "bool",
							BackingName = "_" + char.ToLowerInvariant( name[0] ) + name.Substring( 1 ),
							DefaultLit = el.Props?.ToggleChecked == true ? "true" : "false",
						};
					}
					break;

				case SuiElementType.DropDown:
					{
						var name = SuiNameSanitizer.ToCSharpIdentifier( baseName + "Value" );
						if ( string.IsNullOrEmpty( name ) ) break;
						yield return new InputBindSpec
						{
							FieldName = name,
							CsType = "int",
							BackingName = "_" + char.ToLowerInvariant( name[0] ) + name.Substring( 1 ),
							DefaultLit = (el.Props?.DropDownSelectedIndex ?? 0).ToString( inv ),
						};
					}
					break;

				case SuiElementType.Slider:
					{
						var name = SuiNameSanitizer.ToCSharpIdentifier( baseName + "SliderValue" );
						if ( string.IsNullOrEmpty( name ) ) break;
						yield return new InputBindSpec
						{
							FieldName = name,
							CsType = "float",
							BackingName = "_" + char.ToLowerInvariant( name[0] ) + name.Substring( 1 ),
							DefaultLit = (el.Props?.SliderValue ?? 0f).ToString( "0.###", inv ) + "f",
						};
					}
					break;
			}
		}
	}

	private static void EmitInputBindProperties( SuiDocument doc, StringBuilder sb )
	{
		foreach ( var s in CollectInputBinds( doc ) )
		{
			sb.Append( "\tprivate " ).Append( s.CsType ).Append( ' ' ).Append( s.BackingName )
				.Append( " = " ).Append( s.DefaultLit ).AppendLine( ";" );

			sb.Append( "\t[Property, Group( \"Inputs\" )] public " ).Append( s.CsType )
				.Append( ' ' ).Append( s.FieldName ).AppendLine();
			sb.AppendLine( "\t{" );
			// Read from live View when mounted — that's where two-way `:bind`
			// puts the user-edited value. Fall back to backing field pre-mount.
			sb.Append( "\t\tget => View != null ? View." ).Append( s.FieldName )
				.Append( " : " ).Append( s.BackingName ).AppendLine( ";" );
			sb.AppendLine( "\t\tset" );
			sb.AppendLine( "\t\t{" );
			sb.Append( "\t\t\t" ).Append( s.BackingName ).AppendLine( " = value;" );
			sb.Append( "\t\t\tif ( View != null ) View." ).Append( s.FieldName ).AppendLine( " = value;" );
			sb.AppendLine( "\t\t}" );
			sb.AppendLine( "\t}" );
		}
	}

	private static void EmitInputBindAssignments( SuiDocument doc, StringBuilder sb, string viewVar )
	{
		foreach ( var s in CollectInputBinds( doc ) )
		{
			sb.Append( "\t\t" ).Append( viewVar ).Append( '.' ).Append( s.FieldName )
				.Append( " = " ).Append( s.BackingName ).AppendLine( ";" );
		}
	}

	/// <summary>
	/// V1.5 — for any TwoWay binding with <see cref="SuiBindingUpdateTrigger.Manual"/>
	/// emit a nested <c>ApplyApi</c> sub-object exposed as <c>wrapper.Apply</c>
	/// with one method per Manual-trigger field + <c>.All()</c> shortcut.
	/// Generates NOTHING when the document has no Manual bindings, so the
	/// wrapper API stays clean for documents that don't need it (autocomplete
	/// only shows <c>Apply</c> when there's something to apply).
	///
	/// Pattern:
	///   • TextEntry Manual: reads <c>view.<Name>Ref.Text</c> and writes the bound field
	///   • Slider Manual: calls <c>view.Commit<Name>SliderValue()</c> (panel side
	///     does the actual visual→commit copy)
	/// </summary>
	private static void EmitManualCommitMethods( SuiDocument doc, StringBuilder sb )
	{
		if ( doc?.Elements == null ) return;

		// Collect manual-trigger fields first so we can decide whether to emit
		// the Apply class at all + how to populate .All().
		var manualFields = new System.Collections.Generic.List<(SuiElement El, SuiBinding Binding, string BaseName)>();
		foreach ( var el in doc.Elements )
		{
			if ( el?.Bindings == null ) continue;
			var baseName = el.Name ?? el.Id;
			if ( string.IsNullOrEmpty( baseName ) ) continue;
			foreach ( var b in el.Bindings )
			{
				if ( b?.UpdateTrigger != SuiBindingUpdateTrigger.Manual ) continue;
				var isTextEntry = el.Type == SuiElementType.TextEntry && b.Property == "Value";
				var isSlider = el.Type == SuiElementType.Slider && b.Property == "Value";
				if ( !isTextEntry && !isSlider ) continue;
				manualFields.Add( (el, b, baseName) );
			}
		}

		if ( manualFields.Count == 0 ) return;

		var className = doc?.Output?.ClassName;
		if ( string.IsNullOrEmpty( className ) ) className = "Generated";
		className = SuiNameSanitizer.ToCSharpIdentifier( className );

		sb.AppendLine();
		sb.AppendLine( "\t/// <summary>" );
		sb.AppendLine( "\t/// Manual-commit API for bindings with UpdateTrigger=Manual." );
		sb.AppendLine( "\t/// Call <c>Apply.&lt;FieldName&gt;()</c> to push the widget's current state" );
		sb.AppendLine( "\t/// into its bound Variable; <c>Apply.All()</c> commits every Manual field at once." );
		sb.AppendLine( "\t/// </summary>" );
		sb.AppendLine( "\tprivate ApplyApi _apply;" );
		sb.AppendLine( "\tpublic ApplyApi Apply => _apply ??= new ApplyApi( this );" );

		sb.AppendLine();
		sb.AppendLine( "\tpublic sealed class ApplyApi" );
		sb.AppendLine( "\t{" );
		sb.Append( "\t\tprivate readonly " ).Append( className ).AppendLine( " _w;" );
		sb.Append( "\t\tinternal ApplyApi( " ).Append( className ).AppendLine( " w ) { _w = w; }" );

		var methodNames = new System.Collections.Generic.List<string>();
		foreach ( var (el, b, baseName) in manualFields )
		{
			if ( el.Type == SuiElementType.TextEntry )
			{
				// V1.5-fix — when the element is ALSO exposed-as-variable, the
				// renderer Panel exposes the field under its bare element name
				// (typed Sandbox.UI.TextEntry via the M4 MapElementTypeToRefType
				// addition). The bind emitter suppresses its separate `<Name>Ref`
				// in that case (would otherwise produce a dual `@ref` attribute
				// that breaks Sandbox.UI's parser). The Apply API must reach the
				// SAME field — use the exposed name when exposed, else fall back
				// to the historical `<Name>Ref` suffix.
				var isExposed = el.Flags?.ExposeAsVariable == true && !string.IsNullOrEmpty( el.Name );
				var refName = isExposed
					? SuiNameSanitizer.ToCSharpIdentifier( el.Name )
					: SuiNameSanitizer.ToCSharpIdentifier( baseName + "Ref" );
				var fieldName = SuiNameSanitizer.ToCSharpIdentifier( baseName + "Value" );
				var boundVarName = ResolveBindingVariableName( doc, b );
				if ( string.IsNullOrEmpty( boundVarName ) ) continue;
				sb.AppendLine();
				sb.Append( "\t\tpublic void " ).Append( fieldName ).AppendLine( "()" );
				sb.AppendLine( "\t\t{" );
				sb.AppendLine( "\t\t\tif ( _w.View == null ) return;" );
				sb.Append( "\t\t\tvar entry = _w.View." ).Append( refName ).AppendLine( ";" );
				sb.AppendLine( "\t\t\tif ( entry == null ) return;" );
				// Wrapper-side property setter pushes backing field + View.<Name>.
				sb.Append( "\t\t\t_w." ).Append( boundVarName ).AppendLine( " = entry.Text ?? \"\";" );
				sb.AppendLine( "\t\t}" );
				methodNames.Add( fieldName );
			}
			else if ( el.Type == SuiElementType.Slider )
			{
				var commitField = ResolveBindingVariableName( doc, b ) ?? SuiNameSanitizer.ToCSharpIdentifier( baseName + "SliderValue" );
				var methodName = SuiNameSanitizer.ToCSharpIdentifier( baseName + "Value" );
				sb.AppendLine();
				sb.Append( "\t\tpublic void " ).Append( methodName ).AppendLine( "()" );
				sb.AppendLine( "\t\t{" );
				sb.Append( "\t\t\t_w.View?.Commit" ).Append( commitField ).AppendLine( "();" );
				sb.AppendLine( "\t\t}" );
				methodNames.Add( methodName );
			}
		}

		// `All()` — invoke every field method in declaration order. Useful for
		// "Save" buttons that want to flush every Manual widget at once.
		sb.AppendLine();
		sb.AppendLine( "\t\tpublic void All()" );
		sb.AppendLine( "\t\t{" );
		foreach ( var name in methodNames )
			sb.Append( "\t\t\t" ).Append( name ).AppendLine( "();" );
		sb.AppendLine( "\t\t}" );

		sb.AppendLine( "\t}" );
	}

	private static string ResolveBindingVariableName( SuiDocument doc, SuiBinding b )
	{
		if ( b?.Source == null || string.IsNullOrEmpty( b.Source.VariableId ) ) return null;
		if ( doc?.Variables == null ) return null;
		foreach ( var v in doc.Variables )
			if ( v?.Id == b.Source.VariableId )
				return SuiNameSanitizer.ToCSharpIdentifier( v.Name );
		return null;
	}

	// ─────────────────────────────────────────────────────────────────────
	//  ContentHash override — recursive aggregate for nested re-render
	// ─────────────────────────────────────────────────────────────────────

	private static void EmitContentHash( SuiDocument doc, SuiGenerationContext ctx, StringBuilder sb )
	{
		sb.AppendLine();
		sb.AppendLine( "\tpublic override int ContentHash()" );
		sb.AppendLine( "\t{" );
		sb.AppendLine( "\t\tvar h = new global::System.HashCode();" );

		// V1.5-M2-K7-bugfix — IsShown FIRST so Hide/Show on an embedded wrapper
		// invalidates the parent's BuildHash and triggers a re-render that
		// skips the @if guard around the nested tag. Without this entry the
		// flip is silent and embedded Hide() does nothing visible.
		sb.AppendLine( "\t\th.Add( IsShown );" );

		// Own Manual Variables (every type, public or private — anything that
		// affects rendering needs to contribute).
		if ( doc.Variables != null )
		{
			foreach ( var v in doc.Variables )
			{
				if ( v == null || string.IsNullOrEmpty( v.Name ) ) continue;
				sb.Append( "\t\th.Add( " ).Append( v.Name ).AppendLine( " );" );
			}
		}


		// Recursive child wrappers — single → ContentHash(); ForEach → Count
		// plus a per-item ContentHash() so mutations inside a list item
		// invalidate the parent too.
		if ( doc.Elements != null && ctx?.ResolveReferencedClass != null )
		{
			foreach ( var el in doc.Elements )
			{
				if ( el?.Type != SuiElementType.SuiReference ) continue;
				var data = el.SuiReference;
				if ( data == null || string.IsNullOrEmpty( data.SourceGuid ) ) continue;
				var target = ctx.ResolveReferencedClass( data.SourceGuid );
				if ( target == null || string.IsNullOrEmpty( target.ClassName ) ) continue;
				var fieldName = SuiNameSanitizer.ToCSharpIdentifier( el.Name );
				if ( string.IsNullOrEmpty( fieldName ) ) continue;

				var isForEach = data.ForEach != null && !string.IsNullOrEmpty( data.ForEach.SourceVariableId );
				if ( isForEach )
				{
					sb.Append( "\t\th.Add( " ).Append( fieldName ).AppendLine( "?.Count ?? 0 );" );
					sb.Append( "\t\tif ( " ).Append( fieldName ).AppendLine( " != null )" );
					sb.Append( "\t\t\tforeach ( var __item in " ).Append( fieldName ).AppendLine( " )" );
					sb.AppendLine( "\t\t\t\th.Add( __item?.ContentHash() ?? 0 );" );
				}
				else
				{
					sb.Append( "\t\th.Add( " ).Append( fieldName ).AppendLine( "?.ContentHash() ?? 0 );" );
				}
			}
		}

		sb.AppendLine( "\t\treturn h.ToHashCode();" );
		sb.AppendLine( "\t}" );
	}

	private static void EmitChildReferenceAssignments( SuiDocument doc, SuiGenerationContext ctx, StringBuilder sb, string varName )
	{
		if ( doc?.Elements == null || ctx?.ResolveReferencedClass == null ) return;
		foreach ( var el in doc.Elements )
		{
			if ( el?.Type != SuiElementType.SuiReference ) continue;
			var data = el.SuiReference;
			if ( data == null || string.IsNullOrEmpty( data.SourceGuid ) ) continue;
			var target = ctx.ResolveReferencedClass( data.SourceGuid );
			if ( target == null || string.IsNullOrEmpty( target.ClassName ) ) continue;
			var fieldName = SuiNameSanitizer.ToCSharpIdentifier( el.Name );
			if ( string.IsNullOrEmpty( fieldName ) ) continue;

			sb.Append( "\t\t" ).Append( varName ).Append( '.' ).Append( fieldName )
				.Append( " = " ).Append( fieldName ).AppendLine( ";" );

			// V1.5-M2-K7-bugfix — flag the child wrapper as embedded so its
			// Show()/Hide() don't accidentally spawn a second standalone mount
			// (the duplicate-Hud bug seen in TestInnerHide). ForEach items each
			// need the same flag, hence the conditional walk for lists.
			var isForEach = data.ForEach != null && !string.IsNullOrEmpty( data.ForEach.SourceVariableId );
			if ( isForEach )
			{
				sb.Append( "\t\tif ( " ).Append( fieldName ).AppendLine( " != null )" );
				sb.Append( "\t\t\tforeach ( var __item in " ).Append( fieldName ).AppendLine( " )" );
				sb.AppendLine( "\t\t\t\t__item?.MarkEmbedded();" );
			}
			else
			{
				sb.Append( "\t\t" ).Append( fieldName ).AppendLine( "?.MarkEmbedded();" );
			}
		}
	}
}
