using System.Text;
using SboxUiDesigner.Runtime;

namespace SboxUiDesigner.Generation;

/// <summary>
/// V1.5-M2-K6 — every <c>.sui</c> compile generates a user-facing wrapper
/// class alongside the <c>PanelComponent</c> renderer. One concept, one
/// generated shape, no per-document mode toggle (DEVIATIONS D-013).
///
/// <para>The wrapper class extends <c>SuiPanel&lt;TPanel&gt;</c> (see
/// <c>Code/Runtime/SuiPanel.cs</c>) and provides:
/// <list type="bullet">
///   <item><c>Add()/Show()/Hide()/Remove()</c> — lifetime control.</item>
///   <item>A <c>[Property]</c> field per Manual Variable, mirroring values
///         straight into the live View on <c>SyncFieldsTo</c>.</item>
///   <item>A named-instance <c>[Property]</c> field per <c>SuiReference</c>
///         element on the parent canvas (single instance or
///         <c>List&lt;TChild&gt;</c> when ForEach is enabled), so user code
///         can do <c>parent.ChildName.Var = ...</c>.</item>
/// </list></para>
///
/// <para>The dev declares the wrapper as a <c>[Property]</c> field on their
/// own Component:
/// <code>
///   [Property] public WdgSelectJob Widget { get; set; } = new();
///   void Update() { Widget.Show(); Widget.StaminaRow.StatValue = "75"; }
/// </code></para>
/// </summary>
public static class SuiWrapperEmitter
{
	public static string Emit( SuiDocument doc, SuiGenerationContext ctx = null )
	{
		if ( doc?.Output == null ) return null;

		// Use the sanitized wrapper name the pipeline already produced — falls
		// back to a fresh sanitize of the raw Output.ClassName when ctx is null
		// (called outside the normal pipeline). Without this, names with
		// hyphens / underscores / spaces leak straight into C# and fail.
		var className = !string.IsNullOrEmpty( ctx?.WrapperClassName )
			? ctx.WrapperClassName
			: SuiNameSanitizer.ToCSharpIdentifier( doc.Output.ClassName );
		var ns = doc.Output.Namespace ?? "Game.UI";
		if ( string.IsNullOrEmpty( className ) ) return null;

		var sb = new StringBuilder();
		// SUI ownership header — lets the compile step recognize this file as
		// generated by THIS .sui and safely overwrite it on next compile.
		sb.Append( SuiHeaderEmitter.EmitCsHeader( doc ) );
		sb.AppendLine( "//" );
		sb.AppendLine( "// Wrapper class for the generated PanelComponent. Declare on any Component as:" );
		sb.AppendLine( $"//     [Property] public {className} Widget {{ get; set; }} = new();" );
		sb.AppendLine( "// then drive it from gameplay code:" );
		sb.AppendLine( "//     Widget.Show();                       // mount + visible" );
		sb.AppendLine( "//     Widget.Hide();                       // hide, keep mount" );
		sb.AppendLine( "//     Widget.Remove();                     // destroy mount" );
		sb.AppendLine( "//     Widget.SomeVar = 42;                 // edit a public Variable" );
		sb.AppendLine( "//     Widget.ChildName.NestedVar = \"x\";  // address a SuiReference by name" );
		sb.AppendLine();
		sb.AppendLine( "using System;" );
		sb.AppendLine( "using Sandbox;" );
		sb.AppendLine( "using SboxUiDesigner.Runtime;" );
		sb.AppendLine();
		sb.AppendLine( $"namespace {ns};" );
		sb.AppendLine();
		sb.AppendLine( $"[Title( \"{className}\" )]" );
		sb.AppendLine( $"public sealed class {className} : SuiPanel<{className}Panel>" );
		sb.AppendLine( "{" );

		// Wrapper fields mirror the panel's fields — same names, same types.
		// SyncFieldsTo passes them down by reference so user edits on the
		// wrapper flow into the live view automatically on next render.
		EmitVariableProperties( doc, sb );
		EmitChildReferenceProperties( doc, ctx, sb );
		// V1.5 M3 — Code-mode event slots become wrapper [Property] Action
		// fields that the user assigns (typically via the .partial.cs handler
		// reference). Doo mode lands in Phase 3.
		SuiEventEmitter.EmitWrapperProperties( doc, sb );

		sb.AppendLine();
		sb.AppendLine( $"\tprotected override void SyncFieldsTo( {className}Panel view )" );
		sb.AppendLine( "\t{" );
		EmitVariableAssignments( doc, sb, "view" );
		EmitChildReferenceAssignments( doc, ctx, sb, "view" );
		SuiEventEmitter.EmitWrapperSyncAssignments( doc, sb, "view" );
		sb.AppendLine( "\t}" );

		// V1.5-M2-K7-bugfix — recursive content hash. Without this, mutating a
		// grandchild Variable doesn't change the grandparent Razor's BuildHash
		// (the grandparent only sees its direct child's PublicVariables — the
		// inner ones are invisible). Each wrapper hashes its own Manual
		// Variables plus the recursive ContentHash() of every child wrapper.
		EmitContentHash( doc, ctx, sb );

		sb.AppendLine( "}" );
		return sb.ToString();
	}

	/// <summary>Generated-file name used by the writer. Always <c>&lt;ClassName&gt;.cs</c> in M2-K6.</summary>
	public static string EmitFileName( SuiDocument doc )
	{
		var className = doc?.Output?.ClassName;
		if ( string.IsNullOrEmpty( className ) ) return null;
		// Match what Emit() actually writes — sanitized identifier, not the raw input.
		return SuiNameSanitizer.ToCSharpIdentifier( className ) + ".cs";
	}

	// ─────────────────────────────────────────────────────────────────────
	//  Variables (per Manual SuiVariable in the doc)
	// ─────────────────────────────────────────────────────────────────────

	private static void EmitVariableProperties( SuiDocument doc, StringBuilder sb )
	{
		if ( doc.Variables == null ) return;
		foreach ( var v in doc.Variables )
		{
			if ( v == null || string.IsNullOrEmpty( v.Name ) ) continue;
			if ( (v.Source?.Kind ?? SuiVariableSourceKind.Manual) != SuiVariableSourceKind.Manual ) continue;

			var csType = SuiTypeMapper.ToCSharp( v.Type );
			var def = SuiTypeMapper.DefaultLiteral( v.Type, v.Default );
			var group = v.Group ?? ( v.IsPublic ? "Public" : "Internal" );

			sb.Append( "\t[Property, Group( \"" ).Append( group.Replace( "\"", "\\\"" ) ).Append( "\" )] public " )
				.Append( csType ).Append( ' ' ).Append( v.Name )
				.Append( " { get; set; } = " ).Append( def ).AppendLine( ";" );
		}
	}

	private static void EmitVariableAssignments( SuiDocument doc, StringBuilder sb, string varName )
	{
		if ( doc.Variables == null ) return;
		foreach ( var v in doc.Variables )
		{
			if ( v == null || string.IsNullOrEmpty( v.Name ) ) continue;
			if ( (v.Source?.Kind ?? SuiVariableSourceKind.Manual) != SuiVariableSourceKind.Manual ) continue;
			sb.Append( "\t\t" ).Append( varName ).Append( '.' ).Append( v.Name )
				.Append( " = " ).Append( v.Name ).AppendLine( ";" );
		}
	}

	// ─────────────────────────────────────────────────────────────────────
	//  Named-instance child references (per SuiReference element)
	// ─────────────────────────────────────────────────────────────────────

	private static void EmitChildReferenceProperties( SuiDocument doc, SuiGenerationContext ctx, StringBuilder sb )
	{
		if ( doc?.Elements == null || ctx?.ResolveReferencedClass == null ) return;
		foreach ( var el in doc.Elements )
		{
			if ( el?.Type != SuiElementType.SuiReference ) continue;
			var data = el.SuiReference;
			if ( data == null || string.IsNullOrEmpty( data.SourceGuid ) ) continue;
			var target = ctx.ResolveReferencedClass( data.SourceGuid );
			if ( target == null || string.IsNullOrEmpty( target.ClassName ) ) continue;

			// global:: prefix avoids namespace collisions when the parent
			// namespace contains a prefix of the child's.
			var childWrapperType = string.IsNullOrEmpty( target.Namespace )
				? target.ClassName
				: $"global::{target.Namespace}.{target.ClassName}";
			var fieldName = SuiNameSanitizer.ToCSharpIdentifier( el.Name );
			if ( string.IsNullOrEmpty( fieldName ) ) continue;

			var isForEach = data.ForEach != null && !string.IsNullOrEmpty( data.ForEach.SourceVariableId );
			if ( isForEach )
			{
				sb.Append( "\t[Property, Group( \"Children\" )] public System.Collections.Generic.List<" )
					.Append( childWrapperType ).Append( "> " ).Append( fieldName )
					.AppendLine( " { get; set; } = new();" );
			}
			else
			{
				sb.Append( "\t[Property, Group( \"Children\" )] public " )
					.Append( childWrapperType ).Append( ' ' ).Append( fieldName )
					.Append( " { get; set; } = new " ).Append( childWrapperType ).AppendLine( "();" );
			}
		}
	}

	// ─────────────────────────────────────────────────────────────────────
	//  ContentHash override — recursive aggregate for nested re-render
	// ─────────────────────────────────────────────────────────────────────

	private static void EmitContentHash( SuiDocument doc, SuiGenerationContext ctx, StringBuilder sb )
	{
		sb.AppendLine();
		sb.AppendLine( "\tpublic override int ContentHash()" );
		sb.AppendLine( "\t{" );
		sb.AppendLine( "\t\tvar h = new global::System.HashCode();" );

		// V1.5-M2-K7-bugfix — IsShown FIRST so Hide/Show on an embedded wrapper
		// invalidates the parent's BuildHash and triggers a re-render that
		// skips the @if guard around the nested tag. Without this entry the
		// flip is silent and embedded Hide() does nothing visible.
		sb.AppendLine( "\t\th.Add( IsShown );" );

		// Own Manual Variables (every type, public or private — anything that
		// affects rendering needs to contribute).
		if ( doc.Variables != null )
		{
			foreach ( var v in doc.Variables )
			{
				if ( v == null || string.IsNullOrEmpty( v.Name ) ) continue;
				if ( (v.Source?.Kind ?? SuiVariableSourceKind.Manual) != SuiVariableSourceKind.Manual ) continue;
				sb.Append( "\t\th.Add( " ).Append( v.Name ).AppendLine( " );" );
			}
		}

		// Recursive child wrappers — single → ContentHash(); ForEach → Count
		// plus a per-item ContentHash() so mutations inside a list item
		// invalidate the parent too.
		if ( doc.Elements != null && ctx?.ResolveReferencedClass != null )
		{
			foreach ( var el in doc.Elements )
			{
				if ( el?.Type != SuiElementType.SuiReference ) continue;
				var data = el.SuiReference;
				if ( data == null || string.IsNullOrEmpty( data.SourceGuid ) ) continue;
				var target = ctx.ResolveReferencedClass( data.SourceGuid );
				if ( target == null || string.IsNullOrEmpty( target.ClassName ) ) continue;
				var fieldName = SuiNameSanitizer.ToCSharpIdentifier( el.Name );
				if ( string.IsNullOrEmpty( fieldName ) ) continue;

				var isForEach = data.ForEach != null && !string.IsNullOrEmpty( data.ForEach.SourceVariableId );
				if ( isForEach )
				{
					sb.Append( "\t\th.Add( " ).Append( fieldName ).AppendLine( "?.Count ?? 0 );" );
					sb.Append( "\t\tif ( " ).Append( fieldName ).AppendLine( " != null )" );
					sb.Append( "\t\t\tforeach ( var __item in " ).Append( fieldName ).AppendLine( " )" );
					sb.AppendLine( "\t\t\t\th.Add( __item?.ContentHash() ?? 0 );" );
				}
				else
				{
					sb.Append( "\t\th.Add( " ).Append( fieldName ).AppendLine( "?.ContentHash() ?? 0 );" );
				}
			}
		}

		sb.AppendLine( "\t\treturn h.ToHashCode();" );
		sb.AppendLine( "\t}" );
	}

	private static void EmitChildReferenceAssignments( SuiDocument doc, SuiGenerationContext ctx, StringBuilder sb, string varName )
	{
		if ( doc?.Elements == null || ctx?.ResolveReferencedClass == null ) return;
		foreach ( var el in doc.Elements )
		{
			if ( el?.Type != SuiElementType.SuiReference ) continue;
			var data = el.SuiReference;
			if ( data == null || string.IsNullOrEmpty( data.SourceGuid ) ) continue;
			var target = ctx.ResolveReferencedClass( data.SourceGuid );
			if ( target == null || string.IsNullOrEmpty( target.ClassName ) ) continue;
			var fieldName = SuiNameSanitizer.ToCSharpIdentifier( el.Name );
			if ( string.IsNullOrEmpty( fieldName ) ) continue;

			sb.Append( "\t\t" ).Append( varName ).Append( '.' ).Append( fieldName )
				.Append( " = " ).Append( fieldName ).AppendLine( ";" );

			// V1.5-M2-K7-bugfix — flag the child wrapper as embedded so its
			// Show()/Hide() don't accidentally spawn a second standalone mount
			// (the duplicate-Hud bug seen in TestInnerHide). ForEach items each
			// need the same flag, hence the conditional walk for lists.
			var isForEach = data.ForEach != null && !string.IsNullOrEmpty( data.ForEach.SourceVariableId );
			if ( isForEach )
			{
				sb.Append( "\t\tif ( " ).Append( fieldName ).AppendLine( " != null )" );
				sb.Append( "\t\t\tforeach ( var __item in " ).Append( fieldName ).AppendLine( " )" );
				sb.AppendLine( "\t\t\t\t__item?.MarkEmbedded();" );
			}
			else
			{
				sb.Append( "\t\t" ).Append( fieldName ).AppendLine( "?.MarkEmbedded();" );
			}
		}
	}
}
